name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Compose
      run: docker compose up -d
      
    - name: Wait for services
      run: sleep 45
      
    - name: Run All Tests
      run: |
        pip install pytest pytest-asyncio httpx uuid6
        pytest tests/
        
    - name: Tear down
      run: docker compose down
